import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { AdobeFontScript } from '@/features/adobefont/components/AdobeFontScript'
import { Header } from '@/components/layouts/Header/Header'
import { Footer } from '@/components/layouts/Footer/Footer'
import { PageSection } from '@/components/layouts/PageSection/PageSection'
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <motion.div
      initial={{ opacity: 0 }} // 初期状態
      animate={{ opacity: 1 }} // マウント時
      exit={{ opacity: 0 }}    // アンマウント時
    >
      <Head>
        <title>勝手に鮫町盛り上げ隊について | 勝手に鮫町盛り上げ隊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <AdobeFontScript />
      </Head>
      <Header variant="blue" />
      <main className={[styles.main, styles.about].join(' ')}>
      <PageSection
        bgColor="aliceblue"
        sectionTitle="勝手に鮫町盛り上げ隊について"
        sectionTitleDescription="About"
      >
        {/* キャッチコピー等 */}
        <h3 className={styles.aboutUsCatch}>
          <span>あのね！</span><br />
          <span>鮫町はワクワクが</span><br />
          <span>いっぱいだよ！</span><br /><br />
          <span>そんなワクワクいっぱいな鮫町の</span><br />
          <span>魅力を「活かし」盛り上げたい！</span>
        </h3>
        {/* 説明 */}
        <p className={styles.aboutDescription}>
          勝手に鮫町盛り上げ隊は、
        </p>
      </PageSection>
      </main>
      <Footer />
    </motion.div>
  )
}
