import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { Button } from '@/components/elements/Button/Button'
import { Calendar } from '@/components/elements/Calendar/Calendar'
import { Footer } from '@/components/layouts/Footer/Footer'
import { Header } from '@/components/layouts/Header/Header'
import { MainVisual } from '@/components/elements/MainVisual/MainVisual'
import { PageSection } from '@/components/layouts/PageSection/PageSection'
import { useState, useEffect } from 'react'
import { AdobeFontScript } from '@/features/adobefont/components/AdobeFontScript'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [isHeaderBlue, setIsHeaderBlue] = useState(false)

  const toggleHeaderBlue = () => {
    window.scrollY > Math.round(window.innerHeight)
      ? setIsHeaderBlue(true)
      : setIsHeaderBlue(false)
  }

  useEffect(() => {
    window.addEventListener('scroll', toggleHeaderBlue)
    return () => window.removeEventListener('scroll', toggleHeaderBlue)
  }, [])

  return (
    <>
      <Head>
        <title>TOP | 勝手に鮫町盛り上げ隊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <AdobeFontScript />
      </Head>
      <Header variant={isHeaderBlue ? 'blue' : 'white'} />
      <main className={styles.main}>
        <MainVisual />
        {/*　勝手に鮫町盛り上げ隊について */}
        <PageSection>
          <h2 className={styles.indexAboutUsCatch}>キャッチコピーテキストテキストテキスト</h2>
          <p className={styles.indexAboutUsDescription}>勝手に鮫町盛り上げ隊は…テキストテキストテキスト<br />テキストテキスト<br />テキストテキスト、簡単な説明</p>
          <Button label="勝手に鮫町盛り上げ隊について" />
        </PageSection>
        {/* お知らせ・イベント */}
        <PageSection
          bgColor="aliceblue"
          sectionTitle="お知らせ・イベント"
          sectionTitleDescription="News & Events"
        >
          <div>aaaaa</div>
          <div>aaaaa</div>
          <div>aaaaa</div>
          <div>aaaaa</div>
          <Button label="お知らせ・イベント一覧をみる" />
        </PageSection>
        <PageSection
          sectionTitle="イベントカレンダー"
          sectionTitleDescription="Events Calendar"
        >
          <Calendar />
        </PageSection>
      </main>
      <Footer />
    </>
  )
}
