import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { Button } from '@/components/elements/Button/Button'
import { Calendar } from '@/components/elements/Calendar/Calendar'
import { Footer } from '@/components/layouts/Footer/Footer'
import { Header } from '@/components/layouts/Header/Header'
import { MainVisual } from '@/components/elements/MainVisual/MainVisual'
import { PageSection } from '@/components/layouts/PageSection/PageSection'
import { useState, useEffect } from 'react'
import { AdobeFontScript } from '@/features/adobefont/components/AdobeFontScript'
import { Card } from '@/components/elements/Card/Card'
import { SiteNews } from '@/features/news/components/SiteNews'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [isHeaderBlue, setIsHeaderBlue] = useState(false)

  const toggleHeaderBlue = () => {
    window.scrollY > Math.round(window.innerHeight)
      ? setIsHeaderBlue(true)
      : setIsHeaderBlue(false)
  }

  useEffect(() => {
    window.addEventListener('scroll', toggleHeaderBlue)
    return () => window.removeEventListener('scroll', toggleHeaderBlue)
  }, [])

  const router = useRouter()

  const onClickGotoAbout = (e: any) => {
    e.preventDefault()
    router.push('/about')
  }

  const onClickGotoNews = (e: any) => {
    e.preventDefault()
    router.push('/news')
  }

  return (
    <>
      <Head>
        <title>TOP | 勝手に鮫町盛り上げ隊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <AdobeFontScript />
      </Head>
      <Header variant={isHeaderBlue ? 'blue' : 'white'} />
      <main className={styles.main}>
        <MainVisual />
        {/*　勝手に鮫町盛り上げ隊について */}
        <PageSection>
          <h2 className={styles.indexAboutUsCatch}>鮫町の魅力を活かし、盛り上げる</h2>
          <p className={styles.indexAboutUsDescription}>
            勝手に鮫町盛り上げ隊は…テキストテキストテキスト<br />テキストテキスト<br />テキストテキスト、簡単な説明
          </p>
          <Button label="勝手に鮫町盛り上げ隊について" onClick={onClickGotoAbout} />
        </PageSection>
        {/* お知らせ・イベント */}
        <PageSection
          bgColor="aliceblue"
          sectionTitle="お知らせ・イベント"
          sectionTitleDescription="News & Events"
        >
          <SiteNews limit={3} noPagination={true} />
          <Button label="お知らせ・イベント一覧をみる" onClick={onClickGotoNews} />
        </PageSection>
        <PageSection
          sectionTitle="イベントカレンダー"
          sectionTitleDescription="Events Calendar"
        >
          <Calendar />
        </PageSection>
      </main>
      <Footer />
    </>
  )
}
